# see https://pre-commit.com/hooks.html
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    #-   id: check-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
    -   id: check-added-large-files
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.0.0
    hooks:
    -   id: autoflake
        name: autoflake - remove unused imports and variables
        entry: autoflake --remove-all-unused-imports --recursive --remove-unused-variables --in-place --ignore-init-module-imports
        files: \.py$
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort - sort imports
        entry: isort --profile black --line-length 119
        files: \.py$
        exclude: ^/data-generation/towel/towel/generate_towel_scene.py
        args:
          - --thirdparty=wandb

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        name: black - python code formatter
        entry: black --line-length 119
        files: \.py$
        exclude: ^data-generation/utils/


-   repo: https://github.com/pycqa/flake8
    rev:  6.0.0
    hooks:
    -   id: flake8
        name: flake8 - linter
        exclude: ^data-generation/utils/
